# Generated by Django 3.2.6 on 2021-08-30 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactView',
            new_name='Contact',
        ),
    ]
